### ISSUE TITLE
Build wheel with Threadsafe hdf5 lib

### ISSUE THREAD

**Issue by Coolicedtea** [PyTables/PyTables#1075]
Could we build a wheel for cpython 3.9 with a threadsafe hdf5 lib please. It seems like this was mark completed but wasn't.
https://github.com/PyTables/PyTables/issues/776#issuecomment-1277067497_

**Comment by avalentino** [comment]
Hi @Coolicedtea would you like to submit a pull request for this?

**Comment by Coolicedtea** [comment]
Hi @avalentino, I'm not sure I know how to do this, but my hope is changing https://github.com/PyTables/PyTables/blob/master/ci/github/get_hdf5.sh to include the `--enable-threadsafe` flag for non-parallel builds and pass that to the configure commands would work. https://portal.hdfgroup.org/display/knowledge/Questions+about+thread-safety+and+concurrent+access#Questionsaboutthread-safetyandconcurrentaccess-thread-safety suggests parallel and threadsafe are not compatible. Something like this:
```
EXTRA_MPI_FLAGS=''
EXTRA_SERIAL_FLAGS=""
if [ -z ${HDF5_MPI+x} ]; then
    echo "Building serial"
    EXTRA_SERIAL_FLAGS="--enable-threadsafe"
else
    echo "Building with MPI"
    EXTRA_MPI_FLAGS="--enable-parallel --enable-shared"
fi
...
./configure --prefix="$HDF5_DIR" --with-zlib="$HDF5_DIR" "$EXTRA_MPI_FLAGS" "$EXTRA_SERIAL_FLAGS" --enable-build-mode=production
```
I'm particularly interested in cp39 manylinux2014 x86_64 wheels for 3.6.1+. 
I understand that @tomkooij have worked on this before and would appreciate if anyone could help in getting this built!

**Comment by avalentino** [comment]
@Coolicedtea yes, the one you describe is exactly the approach that i would expect.
... and I would say that once one decides to use the treadsafe build flag it should apply to all the (unix) builds.
If you create a patch on a new branch whose name starts with `ci/` the wheels should be automatically build by GHA and you should be able to download the artefacts and test the directly.

**Comment by Coolicedtea** [comment]
Hi @avalentino, I've created a PR targeting master. I don't have permissions to push to a branch in this repo directly - how do I trigger the builds?

**Comment by avalentino** [comment]
Thanks @Coolicedtea 
I see you branch `ci/threadsafe_hdf5`.
Normally you should the results of the build in https://github.com/Coolicedtea/PyTables/actions
Maybe you should enable action in the settings of your fork.

By the way I have created a copy of your branch and you should see the build [here](https://github.com/avalentino/PyTables/actions/runs/6780789513) in few minutes.

**Comment by Coolicedtea** [comment]
Thanks, I've updated the PR and got GHA to pass https://github.com/Coolicedtea/PyTables/actions on everything except CI with numpy >=2.0dev which I assume is ok. The aarch64 wheels did take a couple hours while to build though.
I've tested the x86_64 linux wheels for cp39 and it works as expected.

Does it look good for a merge? This would close a lot of the outstanding issues with thread safety - is it possible to release?

**Comment by avalentino** [comment]
Dear @Coolicedtea , thanks for taking care of implementing the change.
I have merged your PR #1077.

> This would close a lot of the outstanding issues with thread safety

I would be curious to know more about these "issues with thread safety".
PyTables itself is not thread safe so it is not clear to me what king of issues can be solved just by enabling thread safety on the underling HDF5 library.
Could you please provide more info?
... or, maybe, a ling to a relevant issue?

**Comment by Coolicedtea** [comment]
Hi @avalentino, indeed cases such as concurrent access using the same file handle is still not safe, but other cases are solved with threadsafe hdf5.

This [section of the PyTables docs](https://www.pytables.org/cookbook/threading.html#background) also refer to hdf5 threadsafety issue, which should now be resolved for wheel installations.
For example, this [PyTables example script](https://www.pytables.org/cookbook/threading.html#monkey-patching-pytables) testing concurrent accesses monkey patching PyTables would have been necessary with the latest PyTables build, but I've confirmed it's no longer needed after this change. Monkey patching PyTables led to strange numba compile errors for me so that wasn't a feasible solution. Monkey patching pandas HDFStore may be an okay workaround in this case.

Some outstanding issues, like [this one reported in Pandas](https://github.com/pandas-dev/pandas/issues/12236#issuecomment-426544012) could also be (partially) resolved - from my experience, using a per process locks for reads works in these cases unless mutating, in which case a global lock might be needed. But concurrent reads on different files would be safely supported now.

These documentation references https://www.pytables.org/FAQ.html#can-pytables-be-used-in-concurrent-access-scenarios and
https://github.com/PyTables/PyTables/issues/603#issuecomment-389441654 which claim concurrent reads are ok would now be actually true, at least for reading different h5 files from my testing. This was not the case before, and can be explained by using a [non-threadsafe libhdf5](https://portal.hdfgroup.org/display/knowledge/Questions+about+thread-safety+and+concurrent+access#Questionsaboutthread-safetyandconcurrentaccess-thread-safety) (I think this link stopped working today so found a reference on stackoverflow here: https://stackoverflow.com/a/34913236). This also makes sense based on the details mentioned in the first page of this [libhdf5 RFC](https://docs.hdfgroup.org/hdf5/rfc/RFC_multi_thread.pdf) 

At least for my workflows, using Conda packages for PyTables with libhdf5 which is built with threadsafety worked, but failed if using python wheels. I think it would make development significantly simpler if we don't have to wrap all our hdf5 access call sites, mostly through Pandas HDFStore with a python lock when reading concurrently. This is working with the newer wheels, so I was hoping we could get them officially released.

**Comment by avalentino** [comment]
Thanks for the clarification
